### ISSUE TITLE
[editprofile.go] Erroneous type definition

### ISSUE THREAD

**Issue by morbidslinky** [200106-uta-go/project-3#19]
https://github.com/200106-uta-go/project-3/blob/5b19118f756e1b24926c1e0e3277bc7b1083b25f/pkg/kreate/editprofile.go#L148

There shouldn't be an 'int' type when declaring a loop

**Comment by morbidslinky** [comment]
On it!

**Comment by ghost** [comment]
Fixed now.

**Comment by ghost** [comment]
Hope it didn't hurt buddy.

**Comment by ghost** [comment]
forgot to tell yall why i closed it, but ya its fix my bad on pushing to dev. lets follow orders no. I removed the "int" from the for loop, go does not need to have type defintion when creating a new iterator, types are inferred in go.
