### ISSUE TITLE
[createprofile] when creating profile, the directory is getting duplicated

### ISSUE THREAD

**Issue by mattackard** [200106-uta-go/project-3#24]
![kreateprofile](https://user-images.githubusercontent.com/16366729/76132608-5feb0080-5fd9-11ea-85f1-faa507b87bce.png)

No errors in output, but nano can't open the profile. It looks like the profile may not be created either

To reproduce this error, run `./kreate profile newProfile` or `go run cmd/kreate/*.go profile newProfile`

**Comment by morbidslinky** [comment]
Assigning to Jaeik, Ken and Jessey as per Jaeik's instruction

**Comment by FelicianoEJ** [comment]
Fix on commit b8db03670e8b09c6c42e9132e358a57d6a15b1e0
