### ISSUE TITLE
Missing ".com" at import 

### ISSUE THREAD

**Issue by FelicianoEJ** [200106-uta-go/project-3#25]
Line 9 on internal/app/ingress_controller/proxy/proxy.go

Expected:

"**github.com**/200106-uta-go/project-3/internal/app/ingress_controller/scanner"

On branch dev:

"**github**/200106-uta-go/project-3/internal/app/ingress_controller/scanner"

Just posting this issue since I don't want to mess with the ingress controller code.
Also, I'm not sure how important is this.

**Comment by morbidslinky** [comment]
I think this is the same issue as https://github.com/200106-uta-go/project-3/issues/22

**Comment by FelicianoEJ** [comment]
It's supposed to be fixed but I just checked and the ".com" is still missing on the dev branch.

**Comment by FelicianoEJ** [comment]
https://github.com/200106-uta-go/project-3/blob/4baf0abe012597ad4a0f612740232223b30110c3/internal/app/ingress_controller/proxy/proxy.go#L9

**Comment by morbidslinky** [comment]
We're working on the debug branch, neo is building a Jenkins CI pipeline to regularly integrate our bugfixes from the debug branch to the dev branch

**Comment by FelicianoEJ** [comment]
Cool I'll just leaves it like that then.
