### ISSUE TITLE
[InitializeDirectories] Kreate directories are restricted upon creation

### ISSUE THREAD

**Issue by morbidslinky** [200106-uta-go/project-3#28]
Despite InitializeDirectories setting relaxed permissions for the folders, the created directories are heavily restricted

![Untitled](https://user-images.githubusercontent.com/19238622/76153090-ea406c80-608c-11ea-91eb-bff9b5241799.png)

**Comment by morbidslinky** [comment]
This is probably something wrong with how we're using MkdirAll(). I'll check it out.

**Comment by mattackard** [comment]
If you have to sudo any commands the program runs as root user, so any created directories are set as having root owner

**Comment by morbidslinky** [comment]
The directories are now 0777. We can roll this back if desired, Although I believe 0777 is the standard permission for programs that use var and etc.
