### ISSUE TITLE
[runInstallScript] leaves behind artifacts

### ISSUE THREAD

**Issue by Gamemastertwig** [200106-uta-go/project-3#30]
after running it leaves behind 2 artifacts that need to be removed

> istio-1.4.5 (folder with root control (will need sudo permissions to delete)
> istio-1.4.5.tar.gz (downloaded zip file)

**Comment by Gamemastertwig** [comment]
Available to anyone, if not done by tomorrow will work on it myself

**Comment by JesseyBland** [comment]
I got it!

**Comment by JesseyBland** [comment]
Fixed Issue added removes for tar files
