### ISSUE TITLE
[kreate init] need to get template files into /var/local/kreate/ when initializing the file system

### ISSUE THREAD

**Issue by mattackard** [200106-uta-go/project-3#35]
Currently, if you don't add templates manually to /var/local/kreate/ there won't be any there for create chart to reference. Considering this would ideally be distributed as a binary, it would be best to host the templates somewhere and download the files to /var/local/kreate/ during the initialization.

The templates currently being used for deployment are stored in the deployments/templates/ directory

**Comment by JesseyBland** [comment]
I got this one guys
